### ISSUE TITLE
Create Specification Document

### ISSUE THREAD

**Issue by FabianWilms** [ORFAP/FAP#1]

**Comment by FabianWilms** [comment]
Fill https://github.com/FabianHoltkoetter/ORFAP/blob/master/Documents/RequirementsForCustomer.md with user storys and diagrams for the technical description.

User Stories:

@peter-mueller 
@FabianHoltkoetter

Technical Documentation:

@o4ier 
@Arne2 
@darenegade

**Comment by darenegade** [comment]
Frage zu den User Stories? Wirklich Bar-Graph? Hatte verstanden, dass er ein Line-Graph haben wollte. Vielleicht bieten wir aber auch beides an.

**Comment by darenegade** [comment]
@FabianHoltkoetter User Story 4 ist sehr geil

**Comment by FabianWilms** [comment]
Das war erstmal nur um es zu spezifizieren. Es gibt für beides Anwendungsbeispiele.

**Comment by darenegade** [comment]
Was Unterscheidet UserStory 2 & 3 von 4?
