### ISSUE TITLE
[Backlog 1] Describe design/architecture

### ISSUE THREAD

**Issue by FabianWilms** [ORFAP/FAP#13]

**Comment by peter-mueller** [comment]
![flight-analysis architecture 3](https://docs.google.com/drawings/d/1A_A6YVWHg-Ap_24TBJ1z8XIURnL6FjfMK2ULvhW-9yo/pub?w=960&h=720)

**Comment by peter-mueller** [comment]
The Architecture follows the Microservice Architecture and decomposes the whole application into three major Services that are interconnected by a Hypermedia API (REST maturity 3) and the required infrastructure components.

The Flight Data Service provides an API for storing the relevant Flight Data and accessing it. This service ensures integrity and validity of the Data. Additionally it saves the global User Configurations.

The Transtats Crawler Service provides the functionality to read the current transtats.com Data, transform it as necessary and store it to the Flight Data Service.

The Web-GUI delivers a static (not-templated!) HTML + JS webpage that can be used by the Thin Client as the user frontend. It can make REST requests to the API.

The API Gateway unifies the public API and opens it up to the network on port 80. It may also be used to restrict requests for security reasons (e.g. allow only read on flights).

**Comment by peter-mueller** [comment]
Soll Flight Data Service und Filter Settings Service jetzt getrennt werden oder zusammen bleiben?

@ORFAP/flight-analyzer @ORFAP/flight-data

**Comment by darenegade** [comment]
Streng genommen müssten wir es trennen, aber wir müssen es auch nicht übertreiben und können es zusammen lassen 😉

**Comment by peter-mueller** [comment]
@FabianHoltkoetter 
Vorteile:
- Aufgaben können besser auf das Team verteilt werden.
- Vermischen der verschiedenen Aufgaben kann server seitig nicht passieren, da die Anwendungen getrennt laufen.
- Mehrere Datenbanken, Migration von Bestandsdaten ist einfacher da nur die jeweils betroffene Datenbank aktualisiert werden muss.
- Gibt es momentan Fehler im Filter Service, kann trotzdem noch mit dem Flight Data Service weiterentwickelt werden. Und vice versa
- Einzelne Services können leichter aktuell gehalten werden

Nachteile:
- nicht unbedingt schwierigeres aber aufwändigeres Deployment
- mehr ram

**Comment by darenegade** [comment]
Auch wenn du nur Meinungen von Fabian zulässt:
zu Vort. 1.: Die Aufgaben sind schon gut getrennt. Durch weitere Services wird die Aufgabenverteilung nicht besser, eher schlechter, da der Overhead steigt. Wir reden hier von Services mit +-3 Entitäten. Wir können die Aufgaben ja noch besser trennen, wenn wir für jede Entität einen Service haben.
zu Vort. 2.: Das haben wir so oder so
zu Vort. 3.: Die einzigen Bestandsdaten die wir haben könnten, sind die gespeicherten Filter. Von Transtats brauchen wir keine Bestandsdaten speichern.
zu Vort. 4.: Wenn der Daten Service ausfällt, dann können wir mit den Filtern arbeiten. WOW das ist sehr praktisch.
zu Vort. 5.: Vorteile der Mikroservice Architektur aufzuzählen spricht nicht dafür die Services bis ins kleinste zu zerteilen und weiter zu zerteilen.
zu Nachteilen: Stimme ich zu :wink:

**Comment by FabianWilms** [comment]
Ich habe jetzt erst verstanden was ihr mit dem filter service meint :D finde ich jetzt auch eher wenig sinnvoll in unserem Kontext. Macht nur mehr overhead wie René schon sagte.
