### ISSUE TITLE
[Backlog 3] Description of DataModel

### ISSUE THREAD

**Issue by FabianWilms** [ORFAP/FAP#14]

**Comment by darenegade** [comment]
![model](https://cloud.githubusercontent.com/assets/10849776/14358063/afc10564-fceb-11e5-8f23-38b986966a20.png)

**Comment by peter-mueller** [comment]
Ich glaube nicht nur der Filter soll gespeichert werden, sondern auch die Konfiguration der X/Y Achsen.

Außerdem ist noch wichtig zu wissen ob der Airport des Filters eigenständig ist oder nur eine relation auf die Entity Airport.

**Comment by darenegade** [comment]
Zu 1: Guter Punkt, passe ich noch an.

Zu 2: Wonach sieht es den aus?

**Comment by darenegade** [comment]
Derzeitig finales Modell:

![model](https://cloud.githubusercontent.com/assets/10849776/14528159/7c223e36-024e-11e6-9969-4881c3261dd9.png)
