### ISSUE TITLE
Have a look at data source

### ISSUE THREAD

**Issue by FabianWilms** [ORFAP/FAP#2]
transtats.bts.gov

**Comment by FabianWilms** [comment]
http://www.transtats.bts.gov/Fields.asp?Table_ID=288

hier kriegt man infos über erreichbare flughäfen. hat irgendwer schon rausgefunden wie ich mir die daten dieser table jetz anzeigen lassen kann?

**Comment by FabianWilms** [comment]
http://www.transtats.bts.gov/DL_SelectFields.asp?Table_ID=288 siehe da. `DL_SelectFields.asp` does the magic

**Comment by darenegade** [comment]
Das ist die Anleitung, von der ich in der Vorlesung geredet habe:
https://public.tableau.com/s/blog/2013/08/data-scraping-part-iii-python

**Comment by FabianWilms** [comment]
Genau da hab ich den link mit dem selextFields hergehabt ;)

**Comment by FabianWilms** [comment]
Diese beiden Quellen sollten für den Crawler herangezogen werden:

https://gist.github.com/bbengfort/7322184
https://public.tableau.com/s/blog/2013/08/data-scraping-part-iii-python

@Arne2 
@o4ier
