### ISSUE TITLE
Discuss architectural design and data model

### ISSUE THREAD

**Issue by FabianWilms** [ORFAP/FAP#3]

**Comment by peter-mueller** [comment]
# Vorschlag für eine Microservice-Architektur

![](https://docs.google.com/drawings/d/1A_A6YVWHg-Ap_24TBJ1z8XIURnL6FjfMK2ULvhW-9yo/pub?w=960&h=720)

**Comment by FabianWilms** [comment]
Das REST write geht vermutlich von Crawler -> Redis DB oder?

**Comment by peter-mueller** [comment]
Ja soll ich noch Pfeile machen?

**Comment by peter-mueller** [comment]
Ich würde dann aber eher noch eine Textbeschreibung machen falls wir sowieso was abgeben müssen

**Comment by FabianWilms** [comment]
Die machen wir dann, wenn wir uns für eine Architektur entschieden haben. Kannst gerne noch Pfeile rein machen ^^ und das polymer web Frontend ist irgendwie nicht so ersichtlich dass es das ist was dann auf dem client sichtbar ist

**Comment by peter-mueller** [comment]
# Vorschlag Domain Model
- Erstmal nach Anforderungen (ohne Berücksichtigung transtats)
- DateTime ist evtl. auch nur ein Tag der Woche bin mir da nicht sicher
  ![](https://docs.google.com/drawings/d/1l6dqQ9Wjipkkrh8vveKTkkwZNe1uvwTLddUffwVg1TQ/pub?w=960&h=720)

**Comment by darenegade** [comment]
Ohne Diskussion ist es ja langweilig :wink: , daher hier eine Alternative:
![model](https://cloud.githubusercontent.com/assets/10849776/13906903/3c25fb30-eee2-11e5-81f6-b9515c91a0f5.png)

**Comment by darenegade** [comment]
Fragen/Anmerkungen zur Architektur:
1. Sollte der Flight Data nicht auf den Crawler zugreifen, um die Daten bedarfsgerecht abzufragen. Der Crawler kann natürlich auch die kompletten Daten in einem Rutsch an den Data schicken. Was ist besser?
2. Du umgehst derzeit das API Gateway, dass ist sicher nicht so gedacht :wink:

**Comment by peter-mueller** [comment]
1. Sau gut!! Airline hab ich glatt komplett vergessen :)
2. Den Crawler hab ich als Scheduled Job gesehen ( 1x pro Tag/ pro Monat)
3. Es soll alles vom Client durchs API Gateway gehen und nur GET auf Flight Data erlaubt werden, das ist echt schwer das alles so rein zu malen xD

**Comment by FabianWilms** [comment]
Finde den Crawler als scheduled Job einmal im Monat auch besser.

**Comment by o4ier** [comment]
Evtl kann man http://www.rita.dot.gov/bts/upcoming_data_releases/ auch crawlen, da steht genau drin wann welche Daten ein Update kriegen, und das bis zum Ende des Jahres 2016.
Es werden quasi jede Woche andere Daten eingespielt. Für uns sind da alle intressant bis auf
Airline Full-Time/Part-Time Employment
North American Freight Data
bei folgenden bin ich mir noch nicht sicher:
Airline Financial Data (jedes Quartal)
Transportation Services Index
Bleiben also monatliche Updates für:
Airline Fuel Cost and Consumption
Airline Traffic Data
Passenger Airline Employment
Average Air Fares (jedes Quartal)
Ob die Updatetermine jedes jahr im Voraus festgelegt werden, oder immer +9 Monate in die Zukunft gehen, werden wir noch sehen.
Die Updatetermine selbst haben für mich kein erkennbares Muster (sowas wie "jeden 2. Montag im Monat" oder "Jeden 5.")

**Comment by o4ier** [comment]
Nichtmal die Uhrzeiten bleiben gleich: 11:00 oder 11:30, EDT oder EST, bunt gemischt.
Ich kann aus irgendwelchen Gründen keine meiner Kommentare editieren und diese Reactions funktionieren auch nicht. Weiß der Geier was für einen Third-Party-Kram Github dafür einsetzt, der von meinem Browser geblockt wird :D
Wenn ich meinen User Agent auf Firefox 29 stelle, geht das Editieren... Wenn er auf Firefox 15 steht dann nicht... seltsam, seltsam..

**Comment by darenegade** [comment]
Die Releases zu crawln ist ein guter Weg. :+1:

**Comment by peter-mueller** [comment]
Aber das braucht Zeit das zu schreiben :smile:

**Comment by o4ier** [comment]
Wollen wir eigentlich javadocen oder nicht?
