### ISSUE TITLE
Define Roles

### ISSUE THREAD

**Issue by FabianWilms** [ORFAP/FAP#5]
Define the roles of every member in the team.

**Comment by darenegade** [comment]
Fabian for president 😉

**Comment by darenegade** [comment]
Mit den Wahlspruch: " at least better than trump"

**Comment by o4ier** [comment]
+1

**Comment by Arne2** [comment]
Also wenn wir scrum machen wollen, müssen wir schauen was für eine Sprintlänge wir nehmen sollen (denk mal 1 oder 2 Wochen machen Sinn). Da stellt sich noch die Frage: Müssen wir überhaupt Scrum machen und wollt ihr Scrum machen? (Wer das ganze in englisch haben will, soll auf diese Seite gehen: https://translate.google.de/)

**Comment by Arne2** [comment]
Daily ist halt interessant...

**Comment by FabianWilms** [comment]
Sprint == Zeitraum bis nächste Abgabe, aber Scrum macht keinen Sinn Arne xD

**Comment by darenegade** [comment]
Hat man ja in SE1 schon gemerkt, wie gut Scrum in so einem Kontext funktioniert XD

**Comment by FabianWilms** [comment]
# GUI
- @FabianHoltkoetter
- @peter-mueller 

# Backend
- @darenegade 

# Crawler
- @Arne2 
- @o4ier 

# Arsch vom Dienst

@FabianHoltkoetter

# Integrator

@Arne2
