### ISSUE TITLE
Find a meaningful long version of ORFAP

### ISSUE THREAD

**Issue by o4ier** [ORFAP/FAP#6]
Organization for Realization of FlyAmerica Programs
with their product FlugplanAnalyseProgramm

Yes we are.

**Comment by FabianWilms** [comment]
ORganization For All Purposes

with the product:

Flightdata Analysis Peformer

**Comment by darenegade** [comment]
Original Ridiculous Fancy Application Producer

with

Freaky Analytics Parser

**Comment by FabianHoltkoetter** [comment]
OverRated Fancy Application  Programmers

**Comment by o4ier** [comment]
gefällt mir: ORganization For All Purposes
klingt so bisserl nach ACME - A Company Making Everything

**Comment by Arne2** [comment]
Also das erste, was der Otto genannt hat ist schon seriös. Ist die Frage: Wollen wir das?

**Comment by FabianWilms** [comment]
Abstimmung Firmenname:
http://strawpoll.me/7237590

Abstimmung Produktname:
http://strawpoll.me/7237598

**Comment by FabianWilms** [comment]
Organization For All Purposes
Flugplan Analyse Programm

**Comment by darenegade** [comment]
Ihr seit alle viel zu seriös XD

**Comment by FabianWilms** [comment]
![whatyougonnado](https://i.ytimg.com/vi/LHW3NAtBTrI/maxresdefault.jpg)

**Comment by darenegade** [comment]
Exact XD
