### ISSUE TITLE
Define code style rules

### ISSUE THREAD

**Issue by FabianWilms** [ORFAP/FAP#7]
Ich wäre ja zumindest schonmal für schiedermeier-checkstyle. Alternativen oder abneigung dagegen?

**Comment by peter-mueller** [comment]
https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml Aber mit 4 Leerzeichen Einrückung.

**Comment by FabianWilms** [comment]
Bitte TAB

**Comment by peter-mueller** [comment]
bitte kein tab xD In intellij kann man ja trotzdem mit tab 4 leerzeichen einfügen

**Comment by FabianWilms** [comment]
Tab ist soviel konsistenter. Ich mag keine Leerzeichen :( aber jetzt weis ich wer schuld ist wegen der ständigen Meldung von intellij bei manchen Klassen in gaia xD

**Comment by FabianWilms** [comment]
http://strawpoll.me/7135137

**Comment by darenegade** [comment]
Unabhängig von den Tabs sind die Google Regeln ganz gut. Hauptsächlich weil die schon so schön hier https://google.github.io/styleguide/javaguide.html aufbereitet sind für unsere Doku.

**Comment by o4ier** [comment]
Die Google Regeln gefallen mir auch.
Ob Tab oder x_Leerzeichen ist mir ziemlich egal. Das ist Sache der IDE. (also aus einem Tab x_Leerzeichen zu machen, wenn nötig)

**Comment by Arne2** [comment]
Ah yeah!

> Wildcard imports, static or otherwise, are not used.

**Comment by FabianWilms** [comment]
[Codestieles.pdf](https://github.com/FabianHoltkoetter/ORFAP/files/197562/man.pdf)

**Comment by Arne2** [comment]
Wenn ich dein pdf downloade, dann sagt er mir, dass es beschädigt sei und dass er es nicht öffnen könnte.

**Comment by FabianWilms** [comment]
Deswegen ist es auch nochmal richtig direkt im gut unter docs. Ist außerdem nur die Website als PDF, insofern uninteressant.
